services:
  db:
    image: stevencchang/asgn1mysql:v1
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: webdata
      MYSQL_USER: input
      MYSQL_USER_HOST: '%'
      MYSQL_PASSWORD: password
      MYSQL_USER_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - ./db:/var/lib/mysql
    network_mode: bridge
  app:
    depends_on:
      - db
    image: assignment1_input:v10
    restart: always
    ports:
      - "3001:3001"
    network_mode: bridge
    environment:
      MYSQL_HOST: db
      MYSQL_USER: input
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: webdata
      MYSQL_PORT: 33061