services:
  mysqldb:
    image: stevencchang/asgn1mysql:v1
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_USER_HOST: '%'
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: assignment1_input:v14
    env_file: ./.env
    restart: always
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQLDB_DOCKER_PORT