version: "3.8"
services:
  # web:
  #   container_name: node_app
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./app_code:/app
  #   depends_on:
  #     - mongo
  #   environment:
  #     - SECRET_KEY_BASE=password
  #     - MONGO_URL=mongodb://mongo:27017/
  #   restart: unless-stopped
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGO_INITDB_DATABASE=bmi_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./app_code/database/db:/data/db
      - ./app_code/database/dev.archive:/Databases/dev.archive
      - ./app_code/database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
